default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  adapter: postgresql
  database: shorturl_dev
  host: localhost

test:
  adapter: postgresql
  database: shorturl_test
  host: localhost