# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb25fc05f51d59759885be63b24102698c62ede4f25784909ac4e8f10e017f2f7c3f26e4ed2d491ccfa3f548c40ea54bfd19bbb6fe8740ec946a21fe6ea8314f

test:
  secret_key_base: a06dbe565df7b2d9d4baab8987523a585daed876773ed8de9434565f407196c4efe268465b76d7100077d80bd2bcaed4cbf3692f3ab485f2e8180a4dc092ea4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
